<?xml version="1.0" encoding="utf-8"?><Database Name="Global Environ" Class="JobManagerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=&quot;Global Environ&quot;;Integrated Security=True" SettingsObjectName="JobManager.DAL.Properties.Settings" SettingsPropertyName="Global_EnvironConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Attribute" Member="Attributes">
    <Type Name="Attribute">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="TypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Attribute_Attribute" Member="Attributes" ThisKey="Id" OtherKey="ParentId" Type="Attribute" />
      <Association Name="Attribute_AttributeValue" Member="AttributeValues" ThisKey="Id" OtherKey="AttributeId" Type="AttributeValue" />
      <Association Name="Attribute_MaterialAttribute" Member="MaterialAttributes" ThisKey="Id" OtherKey="AttributeId" Type="MaterialAttribute" />
      <Association Name="Attribute_Attribute" Member="Attribute1" ThisKey="ParentId" OtherKey="Id" Type="Attribute" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AttributeValue" Member="AttributeValues">
    <Type Name="AttributeValue">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="AttributeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParentValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Attribute_AttributeValue" Member="Attribute" ThisKey="AttributeId" OtherKey="Id" Type="Attribute" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Material" Member="Materials">
    <Type Name="Material">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Material_MaterialAttribute" Member="MaterialAttributes" ThisKey="Id" OtherKey="MaterialId" Type="MaterialAttribute" />
      <Association Name="MaterialType_Material" Member="MaterialType" ThisKey="TypeId" OtherKey="Id" Type="MaterialType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MaterialAttributes" Member="MaterialAttributes">
    <Type Name="MaterialAttribute">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaterialId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AttributeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SortOder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsRequired" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Attribute_MaterialAttribute" Member="Attribute" ThisKey="AttributeId" OtherKey="Id" Type="Attribute" IsForeignKey="true" />
      <Association Name="Material_MaterialAttribute" Member="Material" ThisKey="MaterialId" OtherKey="Id" Type="Material" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MaterialType" Member="MaterialTypes">
    <Type Name="MaterialType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="MaterialType_Material" Member="Materials" ThisKey="Id" OtherKey="TypeId" Type="Material" />
    </Type>
  </Table>
  <Function Name="dbo.GetMaterialsForJob" Method="GetMaterialsForJob">
    <Parameter Name="JobId" Parameter="jobId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetMaterialsForJobResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAttributeValues" Method="GetAttributeValues">
    <Parameter Name="AttibuteId" Parameter="attibuteId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAttributeValuesResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAttributesOfMaterial" Method="GetAttributesOfMaterial">
    <Parameter Name="MaterialId" Parameter="materialId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAttributesOfMaterialResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HasChilds" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetChildAttributeValues" Method="GetChildAttributeValues">
    <Parameter Name="ParentAttibuteValueId" Parameter="parentAttibuteValueId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetChildAttributeValuesResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.INSUPDJobMaterial" Method="INSUPDJobMaterial">
    <Parameter Name="JobId" Parameter="jobId" Type="System.Int32" DbType="Int" />
    <Parameter Name="MaterialId" Parameter="materialId" Type="System.Int32" DbType="Int" />
    <Parameter Name="AttributeId" Parameter="attributeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ValueId" Parameter="valueId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Value" Parameter="value" Type="System.String" DbType="VarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DelJobMaterial" Method="DelJobMaterial">
    <Parameter Name="JobId" Parameter="jobId" Type="System.Int32" DbType="Int" />
    <Parameter Name="MaterialId" Parameter="materialId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetJobMaterials" Method="GetJobMaterials">
    <Parameter Name="JobId" Parameter="jobId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetJobMaterialsResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Attributes" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetJobDetails" Method="GetJobDetails">
    <Parameter Name="JobId" Parameter="jobId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetJobDetailsResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="JobName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAllAttributesTypes" Method="GetAllAttributesTypes">
    <ElementType Name="GetAllAttributesTypesResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAllAttributesGrid" Method="GetAllAttributesGrid">
    <ElementType Name="GetAllAttributesGridResult">
      <Column Name="AttributeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AttributeName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="AttributeParentName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="AttributeValueId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AttributeValueName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="AttributeValueParentName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>